### ISSUE TITLE
e2e tests fail on master

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/graph-payments#8]
@andrewgordstewart commented on [Thu Jan 21 2021](https://github.com/statechannels/the-graph/issues/540)

<img width="1228" alt="Screen Shot 2021-01-21 at 4 50 04 PM" src="https://user-images.githubusercontent.com/8432675/105426613-c0daf180-5c08-11eb-9511-7c872ef5c878.png">

Some failing runs:
- https://app.circleci.com/pipelines/github/statechannels/the-graph/2034/workflows/78b5e6ea-6c61-45ce-bc51-ca9943d44178/jobs/8808
- https://app.circleci.com/pipelines/github/statechannels/the-graph/2036/workflows/0cea41f7-8473-43a1-ae4c-ae3e0c7f0f5d/jobs/8822

Note that the failing test is random.

Also note that `406` means `'Payment failed: no channel available'`: https://github.com/statechannels/the-graph/blob/6d6e5961965d3a71f5c239238a77a70cfa103726/packages/e2e-testing/src/payment-server.ts#L226

**Comment by lalexgap** [comment]
Closing as this has been resolved as far as I understand.
