### ISSUE TITLE
Channel Manager no longer needs to store initial state

### ISSUE THREAD

**Issue by lalexgap** [statechannels/graph-payments#9]
**Describe the bug**
Due to recent changes (see https://github.com/statechannels/project-management/issues/42) we no longer need to store the initial ledger state in the channel manager. We should undo that.

[This](https://github.com/statechannels/the-graph/pull/504) is the PR that implemented that behavior.

**Comment by wunnaii** [comment]
link to migrate core channel manager / revisit in sprint 5

**Comment by lalexgap** [comment]
This is now obsolete as the channel manager has been abandoned.
